In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.metrics as ms

In [4]:
df_train=pd.read_csv(r"C:\Users\Lenovo\Desktop\Datas\fraudTrain.csv")
df_train.head()

   Unnamed: 0 trans_date_trans_time  ...  merch_long is_fraud
0           0   2019-01-01 00:00:18  ...  -82.048315        0
1           1   2019-01-01 00:00:44  ... -118.186462        0
2           2   2019-01-01 00:00:51  ... -112.154481        0
3           3   2019-01-01 00:01:16  ... -112.561071        0
4           4   2019-01-01 00:03:06  ...  -78.632459        0

[5 rows x 23 columns]

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [11]:
df_train.drop(columns=['Unnamed: 0'],axis=1,inplace=True)

In [13]:
df_train.head()

  trans_date_trans_time            cc_num  ...  merch_long is_fraud
0   2019-01-01 00:00:18  2703186189652095  ...  -82.048315        0
1   2019-01-01 00:00:44      630423337322  ... -118.186462        0
2   2019-01-01 00:00:51    38859492057661  ... -112.154481        0
3   2019-01-01 00:01:16  3534093764340240  ... -112.561071        0
4   2019-01-01 00:03:06   375534208663984  ...  -78.632459        0

[5 rows x 22 columns]